[package]
build   = "build.rs"
edition = "2021"
name    = "opa-tp"
version = "0.7.5"

[lib]
name = "opa_tp"
path = "src/lib.rs"

[[bin]]
name = "opa-tp"
path = "src/main.rs"
# same output filename as lib target
doc = false


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-stl-client = { workspace = true }
async-trait = { workspace = true }
bytes = { workspace = true }
chronicle-signing = { workspace = true }
chronicle-telemetry = { path = "../chronicle-telemetry" }
clap = { workspace = true, features = ["derive", "env"] }
const_format = { workspace = true }
hex = { workspace = true }
k256 = { workspace = true, features = [
  "default",
  "arithmetic",
  "ecdsa",
  "pkcs8",
  "sha256",
  "std",
  "pem",
] }
opa-tp-protocol = { path = "../opa-tp-protocol" }
prost = { workspace = true }
sawtooth-sdk = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
url = { workspace = true }

[dev-dependencies]
chronicle-telemetry = { path = "../chronicle-telemetry" }
insta               = { workspace = true, features = ["yaml"] }
protobuf            = { workspace = true }
rand                = { workspace = true }
rand_core           = { workspace = true }
