[package]
build   = "build.rs"
edition = "2021"
name    = "opactl"
version = "0.7.5"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-stl-client    = { workspace = true }
async-trait         = { workspace = true }
chronicle-signing   = { workspace = true }
chronicle-telemetry = { path = "../chronicle-telemetry" }
clap                = { version = "4.1.1", features = ["env"] }
common              = { path = "../common" }
const_format        = { workspace = true }
futures             = { workspace = true }
k256                = { workspace = true }
lazy_static         = { workspace = true }
opa-tp-protocol     = { path = "../opa-tp-protocol" }
rand                = { workspace = true }
rand_core           = { workspace = true }
sawtooth-sdk        = { workspace = true }
serde               = { workspace = true }
serde_derive        = { workspace = true }
serde_json          = { workspace = true }
thiserror           = { workspace = true }
tokio               = { workspace = true }
tokio-stream        = { workspace = true }
tracing             = { workspace = true }
url                 = { workspace = true }
user-error          = { workspace = true }
uuid                = { workspace = true }


[dev-dependencies]
hex          = { workspace = true }
insta        = { workspace = true, features = ["yaml"] }
opa-tp       = { path = "../opa-tp" }
portpicker   = { workspace = true }
prost        = { workspace = true }
protobuf     = { workspace = true }
sawtooth-sdk = { workspace = true }
serde_json   = { workspace = true }
tempfile     = { workspace = true }
tmq          = { workspace = true }

[features]
tokio-tracing = ["chronicle-telemetry/tokio-tracing"]
